/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScreenerRouteImport } from './routes/screener'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as BacktestRouteImport } from './routes/backtest'
import { Route as AiInsightsRouteImport } from './routes/ai-insights'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FundIdRouteImport } from './routes/fund.$id'
import { Route as ApiPublicMarketTicksRouteImport } from './routes/api/public/market-ticks'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenerRoute = ScreenerRouteImport.update({
  id: '/screener',
  path: '/screener',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestRoute = BacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => rootRouteImport,
} as any)
const AiInsightsRoute = AiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FundIdRoute = FundIdRouteImport.update({
  id: '/fund/$id',
  path: '/fund/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMarketTicksRoute = ApiPublicMarketTicksRouteImport.update({
  id: '/api/public/market-ticks',
  path: '/api/public/market-ticks',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-insights': typeof AiInsightsRoute
  '/backtest': typeof BacktestRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/explorer': typeof ExplorerRoute
  '/portfolio': typeof PortfolioRoute
  '/rankings': typeof RankingsRoute
  '/screener': typeof ScreenerRoute
  '/settings': typeof SettingsRoute
  '/fund/$id': typeof FundIdRoute
  '/api/public/market-ticks': typeof ApiPublicMarketTicksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-insights': typeof AiInsightsRoute
  '/backtest': typeof BacktestRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/explorer': typeof ExplorerRoute
  '/portfolio': typeof PortfolioRoute
  '/rankings': typeof RankingsRoute
  '/screener': typeof ScreenerRoute
  '/settings': typeof SettingsRoute
  '/fund/$id': typeof FundIdRoute
  '/api/public/market-ticks': typeof ApiPublicMarketTicksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-insights': typeof AiInsightsRoute
  '/backtest': typeof BacktestRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/explorer': typeof ExplorerRoute
  '/portfolio': typeof PortfolioRoute
  '/rankings': typeof RankingsRoute
  '/screener': typeof ScreenerRoute
  '/settings': typeof SettingsRoute
  '/fund/$id': typeof FundIdRoute
  '/api/public/market-ticks': typeof ApiPublicMarketTicksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-insights'
    | '/backtest'
    | '/compare'
    | '/dashboard'
    | '/explorer'
    | '/portfolio'
    | '/rankings'
    | '/screener'
    | '/settings'
    | '/fund/$id'
    | '/api/public/market-ticks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-insights'
    | '/backtest'
    | '/compare'
    | '/dashboard'
    | '/explorer'
    | '/portfolio'
    | '/rankings'
    | '/screener'
    | '/settings'
    | '/fund/$id'
    | '/api/public/market-ticks'
  id:
    | '__root__'
    | '/'
    | '/ai-insights'
    | '/backtest'
    | '/compare'
    | '/dashboard'
    | '/explorer'
    | '/portfolio'
    | '/rankings'
    | '/screener'
    | '/settings'
    | '/fund/$id'
    | '/api/public/market-ticks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiInsightsRoute: typeof AiInsightsRoute
  BacktestRoute: typeof BacktestRoute
  CompareRoute: typeof CompareRoute
  DashboardRoute: typeof DashboardRoute
  ExplorerRoute: typeof ExplorerRoute
  PortfolioRoute: typeof PortfolioRoute
  RankingsRoute: typeof RankingsRoute
  ScreenerRoute: typeof ScreenerRoute
  SettingsRoute: typeof SettingsRoute
  FundIdRoute: typeof FundIdRoute
  ApiPublicMarketTicksRoute: typeof ApiPublicMarketTicksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screener': {
      id: '/screener'
      path: '/screener'
      fullPath: '/screener'
      preLoaderRoute: typeof ScreenerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtest': {
      id: '/backtest'
      path: '/backtest'
      fullPath: '/backtest'
      preLoaderRoute: typeof BacktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-insights': {
      id: '/ai-insights'
      path: '/ai-insights'
      fullPath: '/ai-insights'
      preLoaderRoute: typeof AiInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fund/$id': {
      id: '/fund/$id'
      path: '/fund/$id'
      fullPath: '/fund/$id'
      preLoaderRoute: typeof FundIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/market-ticks': {
      id: '/api/public/market-ticks'
      path: '/api/public/market-ticks'
      fullPath: '/api/public/market-ticks'
      preLoaderRoute: typeof ApiPublicMarketTicksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiInsightsRoute: AiInsightsRoute,
  BacktestRoute: BacktestRoute,
  CompareRoute: CompareRoute,
  DashboardRoute: DashboardRoute,
  ExplorerRoute: ExplorerRoute,
  PortfolioRoute: PortfolioRoute,
  RankingsRoute: RankingsRoute,
  ScreenerRoute: ScreenerRoute,
  SettingsRoute: SettingsRoute,
  FundIdRoute: FundIdRoute,
  ApiPublicMarketTicksRoute: ApiPublicMarketTicksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
