/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScreenerRouteImport } from './routes/screener'
import { Route as ReturnsHistoricalRouteImport } from './routes/returns-historical'
import { Route as ResearchDeskRouteImport } from './routes/research-desk'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as BacktestRouteImport } from './routes/backtest'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FundIdRouteImport } from './routes/fund.$id'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as ApiPublicSchemeTerRouteImport } from './routes/api/public/scheme-ter'
import { Route as ApiPublicSchemeAumRouteImport } from './routes/api/public/scheme-aum'
import { Route as ApiPublicNavBatchRouteImport } from './routes/api/public/nav-batch'
import { Route as ApiPublicMarketTicksRouteImport } from './routes/api/public/market-ticks'
import { Route as ApiPublicAmfiNavallRouteImport } from './routes/api/public/amfi-navall'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenerRoute = ScreenerRouteImport.update({
  id: '/screener',
  path: '/screener',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsHistoricalRoute = ReturnsHistoricalRouteImport.update({
  id: '/returns-historical',
  path: '/returns-historical',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchDeskRoute = ResearchDeskRouteImport.update({
  id: '/research-desk',
  path: '/research-desk',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestRoute = BacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FundIdRoute = FundIdRouteImport.update({
  id: '/fund/$id',
  path: '/fund/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSchemeTerRoute = ApiPublicSchemeTerRouteImport.update({
  id: '/api/public/scheme-ter',
  path: '/api/public/scheme-ter',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSchemeAumRoute = ApiPublicSchemeAumRouteImport.update({
  id: '/api/public/scheme-aum',
  path: '/api/public/scheme-aum',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNavBatchRoute = ApiPublicNavBatchRouteImport.update({
  id: '/api/public/nav-batch',
  path: '/api/public/nav-batch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMarketTicksRoute = ApiPublicMarketTicksRouteImport.update({
  id: '/api/public/market-ticks',
  path: '/api/public/market-ticks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAmfiNavallRoute = ApiPublicAmfiNavallRouteImport.update({
  id: '/api/public/amfi-navall',
  path: '/api/public/amfi-navall',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backtest': typeof BacktestRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/explorer': typeof ExplorerRoute
  '/mcp': typeof McpRoute
  '/methodology': typeof MethodologyRoute
  '/portfolio': typeof PortfolioRoute
  '/rankings': typeof RankingsRoute
  '/research-desk': typeof ResearchDeskRoute
  '/returns-historical': typeof ReturnsHistoricalRoute
  '/screener': typeof ScreenerRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/fund/$id': typeof FundIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/amfi-navall': typeof ApiPublicAmfiNavallRoute
  '/api/public/market-ticks': typeof ApiPublicMarketTicksRoute
  '/api/public/nav-batch': typeof ApiPublicNavBatchRoute
  '/api/public/scheme-aum': typeof ApiPublicSchemeAumRoute
  '/api/public/scheme-ter': typeof ApiPublicSchemeTerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backtest': typeof BacktestRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/explorer': typeof ExplorerRoute
  '/mcp': typeof McpRoute
  '/methodology': typeof MethodologyRoute
  '/portfolio': typeof PortfolioRoute
  '/rankings': typeof RankingsRoute
  '/research-desk': typeof ResearchDeskRoute
  '/returns-historical': typeof ReturnsHistoricalRoute
  '/screener': typeof ScreenerRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/fund/$id': typeof FundIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/amfi-navall': typeof ApiPublicAmfiNavallRoute
  '/api/public/market-ticks': typeof ApiPublicMarketTicksRoute
  '/api/public/nav-batch': typeof ApiPublicNavBatchRoute
  '/api/public/scheme-aum': typeof ApiPublicSchemeAumRoute
  '/api/public/scheme-ter': typeof ApiPublicSchemeTerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backtest': typeof BacktestRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/explorer': typeof ExplorerRoute
  '/mcp': typeof McpRoute
  '/methodology': typeof MethodologyRoute
  '/portfolio': typeof PortfolioRoute
  '/rankings': typeof RankingsRoute
  '/research-desk': typeof ResearchDeskRoute
  '/returns-historical': typeof ReturnsHistoricalRoute
  '/screener': typeof ScreenerRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/fund/$id': typeof FundIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/amfi-navall': typeof ApiPublicAmfiNavallRoute
  '/api/public/market-ticks': typeof ApiPublicMarketTicksRoute
  '/api/public/nav-batch': typeof ApiPublicNavBatchRoute
  '/api/public/scheme-aum': typeof ApiPublicSchemeAumRoute
  '/api/public/scheme-ter': typeof ApiPublicSchemeTerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backtest'
    | '/compare'
    | '/dashboard'
    | '/explorer'
    | '/mcp'
    | '/methodology'
    | '/portfolio'
    | '/rankings'
    | '/research-desk'
    | '/returns-historical'
    | '/screener'
    | '/settings'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/fund/$id'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/amfi-navall'
    | '/api/public/market-ticks'
    | '/api/public/nav-batch'
    | '/api/public/scheme-aum'
    | '/api/public/scheme-ter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backtest'
    | '/compare'
    | '/dashboard'
    | '/explorer'
    | '/mcp'
    | '/methodology'
    | '/portfolio'
    | '/rankings'
    | '/research-desk'
    | '/returns-historical'
    | '/screener'
    | '/settings'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/fund/$id'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/amfi-navall'
    | '/api/public/market-ticks'
    | '/api/public/nav-batch'
    | '/api/public/scheme-aum'
    | '/api/public/scheme-ter'
  id:
    | '__root__'
    | '/'
    | '/backtest'
    | '/compare'
    | '/dashboard'
    | '/explorer'
    | '/mcp'
    | '/methodology'
    | '/portfolio'
    | '/rankings'
    | '/research-desk'
    | '/returns-historical'
    | '/screener'
    | '/settings'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/fund/$id'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/amfi-navall'
    | '/api/public/market-ticks'
    | '/api/public/nav-batch'
    | '/api/public/scheme-aum'
    | '/api/public/scheme-ter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BacktestRoute: typeof BacktestRoute
  CompareRoute: typeof CompareRoute
  DashboardRoute: typeof DashboardRoute
  ExplorerRoute: typeof ExplorerRoute
  McpRoute: typeof McpRoute
  MethodologyRoute: typeof MethodologyRoute
  PortfolioRoute: typeof PortfolioRoute
  RankingsRoute: typeof RankingsRoute
  ResearchDeskRoute: typeof ResearchDeskRoute
  ReturnsHistoricalRoute: typeof ReturnsHistoricalRoute
  ScreenerRoute: typeof ScreenerRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  FundIdRoute: typeof FundIdRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicAmfiNavallRoute: typeof ApiPublicAmfiNavallRoute
  ApiPublicMarketTicksRoute: typeof ApiPublicMarketTicksRoute
  ApiPublicNavBatchRoute: typeof ApiPublicNavBatchRoute
  ApiPublicSchemeAumRoute: typeof ApiPublicSchemeAumRoute
  ApiPublicSchemeTerRoute: typeof ApiPublicSchemeTerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screener': {
      id: '/screener'
      path: '/screener'
      fullPath: '/screener'
      preLoaderRoute: typeof ScreenerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns-historical': {
      id: '/returns-historical'
      path: '/returns-historical'
      fullPath: '/returns-historical'
      preLoaderRoute: typeof ReturnsHistoricalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research-desk': {
      id: '/research-desk'
      path: '/research-desk'
      fullPath: '/research-desk'
      preLoaderRoute: typeof ResearchDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtest': {
      id: '/backtest'
      path: '/backtest'
      fullPath: '/backtest'
      preLoaderRoute: typeof BacktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fund/$id': {
      id: '/fund/$id'
      path: '/fund/$id'
      fullPath: '/fund/$id'
      preLoaderRoute: typeof FundIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/scheme-ter': {
      id: '/api/public/scheme-ter'
      path: '/api/public/scheme-ter'
      fullPath: '/api/public/scheme-ter'
      preLoaderRoute: typeof ApiPublicSchemeTerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/scheme-aum': {
      id: '/api/public/scheme-aum'
      path: '/api/public/scheme-aum'
      fullPath: '/api/public/scheme-aum'
      preLoaderRoute: typeof ApiPublicSchemeAumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/nav-batch': {
      id: '/api/public/nav-batch'
      path: '/api/public/nav-batch'
      fullPath: '/api/public/nav-batch'
      preLoaderRoute: typeof ApiPublicNavBatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/market-ticks': {
      id: '/api/public/market-ticks'
      path: '/api/public/market-ticks'
      fullPath: '/api/public/market-ticks'
      preLoaderRoute: typeof ApiPublicMarketTicksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/amfi-navall': {
      id: '/api/public/amfi-navall'
      path: '/api/public/amfi-navall'
      fullPath: '/api/public/amfi-navall'
      preLoaderRoute: typeof ApiPublicAmfiNavallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BacktestRoute: BacktestRoute,
  CompareRoute: CompareRoute,
  DashboardRoute: DashboardRoute,
  ExplorerRoute: ExplorerRoute,
  McpRoute: McpRoute,
  MethodologyRoute: MethodologyRoute,
  PortfolioRoute: PortfolioRoute,
  RankingsRoute: RankingsRoute,
  ResearchDeskRoute: ResearchDeskRoute,
  ReturnsHistoricalRoute: ReturnsHistoricalRoute,
  ScreenerRoute: ScreenerRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  FundIdRoute: FundIdRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicAmfiNavallRoute: ApiPublicAmfiNavallRoute,
  ApiPublicMarketTicksRoute: ApiPublicMarketTicksRoute,
  ApiPublicNavBatchRoute: ApiPublicNavBatchRoute,
  ApiPublicSchemeAumRoute: ApiPublicSchemeAumRoute,
  ApiPublicSchemeTerRoute: ApiPublicSchemeTerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
