/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScreenerRouteImport } from './routes/screener'
import { Route as ResearchDeskRouteImport } from './routes/research-desk'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ReturnsHistoricalRouteImport } from './routes/returns-historical'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as BacktestRouteImport } from './routes/backtest'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FundIdRouteImport } from './routes/fund.$id'
import { Route as ApiPublicSchemeAumRouteImport } from './routes/api/public/scheme-aum'
import { Route as ApiPublicMarketTicksRouteImport } from './routes/api/public/market-ticks'
import { Route as ApiPublicAmfiNavallRouteImport } from './routes/api/public/amfi-navall'
import { Route as ApiPublicNavBatchRouteImport } from './routes/api/public/nav-batch'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenerRoute = ScreenerRouteImport.update({
  id: '/screener',
  path: '/screener',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchDeskRoute = ResearchDeskRouteImport.update({
  id: '/research-desk',
  path: '/research-desk',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsHistoricalRoute = ReturnsHistoricalRouteImport.update({
  id: '/returns-historical',
  path: '/returns-historical',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestRoute = BacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FundIdRoute = FundIdRouteImport.update({
  id: '/fund/$id',
  path: '/fund/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSchemeAumRoute = ApiPublicSchemeAumRouteImport.update({
  id: '/api/public/scheme-aum',
  path: '/api/public/scheme-aum',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMarketTicksRoute = ApiPublicMarketTicksRouteImport.update({
  id: '/api/public/market-ticks',
  path: '/api/public/market-ticks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAmfiNavallRoute = ApiPublicAmfiNavallRouteImport.update({
  id: '/api/public/amfi-navall',
  path: '/api/public/amfi-navall',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNavBatchRoute = ApiPublicNavBatchRouteImport.update({
  id: '/api/public/nav-batch',
  path: '/api/public/nav-batch',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/returns-historical': typeof ReturnsHistoricalRoute
  '/backtest': typeof BacktestRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/explorer': typeof ExplorerRoute
  '/portfolio': typeof PortfolioRoute
  '/rankings': typeof RankingsRoute
  '/research-desk': typeof ResearchDeskRoute
  '/screener': typeof ScreenerRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/fund/$id': typeof FundIdRoute
  '/api/public/amfi-navall': typeof ApiPublicAmfiNavallRoute
  '/api/public/market-ticks': typeof ApiPublicMarketTicksRoute
  '/api/public/scheme-aum': typeof ApiPublicSchemeAumRoute
  '/api/public/nav-batch': typeof ApiPublicNavBatchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/returns-historical': typeof ReturnsHistoricalRoute
  '/backtest': typeof BacktestRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/explorer': typeof ExplorerRoute
  '/portfolio': typeof PortfolioRoute
  '/rankings': typeof RankingsRoute
  '/research-desk': typeof ResearchDeskRoute
  '/screener': typeof ScreenerRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/fund/$id': typeof FundIdRoute
  '/api/public/amfi-navall': typeof ApiPublicAmfiNavallRoute
  '/api/public/market-ticks': typeof ApiPublicMarketTicksRoute
  '/api/public/scheme-aum': typeof ApiPublicSchemeAumRoute
  '/api/public/nav-batch': typeof ApiPublicNavBatchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/returns-historical': typeof ReturnsHistoricalRoute
  '/backtest': typeof BacktestRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/explorer': typeof ExplorerRoute
  '/portfolio': typeof PortfolioRoute
  '/rankings': typeof RankingsRoute
  '/research-desk': typeof ResearchDeskRoute
  '/screener': typeof ScreenerRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/fund/$id': typeof FundIdRoute
  '/api/public/amfi-navall': typeof ApiPublicAmfiNavallRoute
  '/api/public/market-ticks': typeof ApiPublicMarketTicksRoute
  '/api/public/scheme-aum': typeof ApiPublicSchemeAumRoute
  '/api/public/nav-batch': typeof ApiPublicNavBatchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backtest'
    | '/compare'
    | '/dashboard'
    | '/explorer'
    | '/portfolio'
    | '/rankings'
    | '/research-desk'
    | '/screener'
    | '/settings'
    | '/sitemap.xml'
    | '/fund/$id'
    | '/api/public/amfi-navall'
    | '/api/public/market-ticks'
    | '/api/public/scheme-aum'
    | '/api/public/nav-batch'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backtest'
    | '/compare'
    | '/dashboard'
    | '/explorer'
    | '/portfolio'
    | '/rankings'
    | '/research-desk'
    | '/screener'
    | '/settings'
    | '/sitemap.xml'
    | '/fund/$id'
    | '/api/public/amfi-navall'
    | '/api/public/market-ticks'
    | '/api/public/scheme-aum'
    | '/api/public/nav-batch'
  id:
    | '__root__'
    | '/'
    | '/backtest'
    | '/compare'
    | '/dashboard'
    | '/explorer'
    | '/portfolio'
    | '/rankings'
    | '/research-desk'
    | '/screener'
    | '/settings'
    | '/sitemap.xml'
    | '/fund/$id'
    | '/api/public/amfi-navall'
    | '/api/public/market-ticks'
    | '/api/public/scheme-aum'
    | '/api/public/nav-batch'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BacktestRoute: typeof BacktestRoute
  CompareRoute: typeof CompareRoute
  DashboardRoute: typeof DashboardRoute
  ExplorerRoute: typeof ExplorerRoute
  PortfolioRoute: typeof PortfolioRoute
  RankingsRoute: typeof RankingsRoute
  ResearchDeskRoute: typeof ResearchDeskRoute
  ScreenerRoute: typeof ScreenerRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  FundIdRoute: typeof FundIdRoute
  ApiPublicAmfiNavallRoute: typeof ApiPublicAmfiNavallRoute
  ApiPublicMarketTicksRoute: typeof ApiPublicMarketTicksRoute
  ApiPublicSchemeAumRoute: typeof ApiPublicSchemeAumRoute
  ApiPublicNavBatchRoute: typeof ApiPublicNavBatchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screener': {
      id: '/screener'
      path: '/screener'
      fullPath: '/screener'
      preLoaderRoute: typeof ScreenerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research-desk': {
      id: '/research-desk'
      path: '/research-desk'
      fullPath: '/research-desk'
      preLoaderRoute: typeof ResearchDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtest': {
      id: '/backtest'
      path: '/backtest'
      fullPath: '/backtest'
      preLoaderRoute: typeof BacktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fund/$id': {
      id: '/fund/$id'
      path: '/fund/$id'
      fullPath: '/fund/$id'
      preLoaderRoute: typeof FundIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/scheme-aum': {
      id: '/api/public/scheme-aum'
      path: '/api/public/scheme-aum'
      fullPath: '/api/public/scheme-aum'
      preLoaderRoute: typeof ApiPublicSchemeAumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/market-ticks': {
      id: '/api/public/market-ticks'
      path: '/api/public/market-ticks'
      fullPath: '/api/public/market-ticks'
      preLoaderRoute: typeof ApiPublicMarketTicksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/amfi-navall': {
      id: '/api/public/amfi-navall'
      path: '/api/public/amfi-navall'
      fullPath: '/api/public/amfi-navall'
      preLoaderRoute: typeof ApiPublicAmfiNavallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/nav-batch': {
      id: '/api/public/nav-batch'
      path: '/api/public/nav-batch'
      fullPath: '/api/public/nav-batch'
      preLoaderRoute: typeof ApiPublicNavBatchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ReturnsHistoricalRoute,
  MethodologyRoute,
  IndexRoute: IndexRoute,
  BacktestRoute: BacktestRoute,
  CompareRoute: CompareRoute,
  DashboardRoute: DashboardRoute,
  ExplorerRoute: ExplorerRoute,
  PortfolioRoute: PortfolioRoute,
  RankingsRoute: RankingsRoute,
  ResearchDeskRoute: ResearchDeskRoute,
  ScreenerRoute: ScreenerRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  FundIdRoute: FundIdRoute,
  ApiPublicAmfiNavallRoute: ApiPublicAmfiNavallRoute,
  ApiPublicMarketTicksRoute: ApiPublicMarketTicksRoute,
  ApiPublicSchemeAumRoute: ApiPublicSchemeAumRoute,
  ApiPublicNavBatchRoute: ApiPublicNavBatchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
